export const FETCH_NEW_MESSAGES = 'FETCH_NEW_MESSAGES';
export const FETCH_OLD_MESSAGES = 'FETCH_OLD_MESSAGES';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SOCKET_SEND_MESSAGE = 'SOCKET_SEND_MESSAGE';
export const SOCKET_BROADCAST_SEND_MESSAGE = 'SOCKET_BROADCAST_SEND_MESSAGE';
export const SOCKET_BROADCAST_NOTIFY_MESSAGE = 'SOCKET_BROADCAST_NOTIFY_MESSAGE';
