export const FETCH_CHAT_ROOMS = 'FETCH_CHAT_ROOMS';
export const CREATE_CHAT_ROOM = 'CREATE_CHAT_ROOM';
export const SOCKET_JOIN_CHAT_ROOM = 'SOCKET_JOIN_CHAT_ROOM';
export const SOCKET_LEAVE_CHAT_ROOM = 'SOCKET_LEAVE_CHAT_ROOM';
export const RECEIVE_CHAT_ROOM = 'RECEIVE_CHAT_ROOM';
