// Local login
export const LOCAL_LOGIN_PENDING = 'LOCAL_LOGIN_PENDING';
export const LOCAL_LOGIN_FULFILLED = 'LOCAL_LOGIN_FULFILLED';
export const LOCAL_LOGIN_REJECTED = 'LOCAL_LOGIN_REJECTED';

// Facebook login
export const FACEBOOK_LOGIN_PENDING = 'FACEBOOK_LOGIN_PENDING';
export const FACEBOOK_LOGIN_FULFILLED = 'FACEBOOK_LOGIN_FULFILLED';
export const FACEBOOK_LOGIN_REJECTED = 'FACEBOOK_LOGIN_REJECTED';

// Google login
export const GOOGLE_LOGIN_PENDING = 'GOOGLE_LOGIN_PENDING';
export const GOOGLE_LOGIN_FULFILLED = 'GOOGLE_LOGIN_FULFILLED';
export const GOOGLE_LOGIN_REJECTED = 'GOOGLE_LOGIN_REJECTED';

// Twitter login
export const TWITTER_LOGIN_PENDING = 'TWITTER_LOGIN_PENDING';
export const TWITTER_LOGIN_FULFILLED = 'TWITTER_LOGIN_FULFILLED';
export const TWITTER_LOGIN_REJECTED = 'TWITTER_LOGIN_REJECTED';

// Register
export const REGISTER_PENDING = 'REGISTER_PENDING';
export const REGISTER_FULFILLED = 'REGISTER_FULFILLED';
export const REGISTER_REJECTED = 'REGISTER_REJECTED';

// Logout
export const LOGOUT_PENDING = 'LOGOUT_PENDING';
export const LOGOUT_FULFILLED = 'LOGOUT_FULFILLED';
export const LOGOUT_REJECTED = 'LOGOUT_REJECTED';