// Local login
export const LOCAL_LOGIN_PENDING = 'LOCAL_LOGIN_PENDING';
export const LOCAL_LOGIN_FULFILLED = 'LOCAL_LOGIN_FULFILLED';
export const LOCAL_LOGIN_REJECTED = 'LOCAL_LOGIN_REJECTED';

// Register
export const REGISTER_PENDING = 'REGISTER_PENDING';
export const REGISTER_FULFILLED = 'REGISTER_FULFILLED';
export const REGISTER_REJECTED = 'REGISTER_REJECTED';

// Logout
export const LOGOUT_PENDING = 'LOGOUT_PENDING';
export const LOGOUT_FULFILLED = 'LOGOUT_FULFILLED';
export const LOGOUT_REJECTED = 'LOGOUT_REJECTED';