export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SOCKET_SEND_MESSAGE = 'SOCKET_SEND_MESSAGE';
export const SOCKET_BROADCAST_SEND_MESSAGE = 'SOCKET_BROADCAST_SEND_MESSAGE';
export const SOCKET_BROADCAST_NOTIFY_MESSAGE = 'SOCKET_BROADCAST_NOTIFY_MESSAGE';
