export const FETCH_CHAT_ROOMS_COUNT = 'FETCH_CHAT_ROOMS_COUNT';
export const FETCH_SELECTED_CHAT_ROOM = 'FETCH_SELECTED_CHAT_ROOM';
export const FETCH_CHAT_ROOMS = 'FETCH_CHAT_ROOMS';
export const CREATE_CHAT_ROOM = 'CREATE_CHAT_ROOM';
export const EDIT_CHAT_ROOM = 'EDIT_CHAT_ROOM';
export const DELETE_CHAT_ROOM = 'DELETE_CHAT_ROOM';
