export const FETCH_ACTIVE_USER = 'FETCH_ACTIVE_USER';
export const FETCH_SELECTED_USER = 'FETCH_SELECTED_USER';
export const FETCH_USERS = 'FETCH_USERS';
export const CREATE_USER = 'CREATE_USER';
export const EDIT_USER = 'EDIT_USER';
export const DELETE_USER = 'DELETE_USER';
