export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';
export const SOCKET_USER_LOGIN = 'SOCKET_USER_LOGIN';
export const SOCKET_BROADCAST_USER_LOGIN = 'SOCKET_BROADCAST_USER_LOGIN';
export const SOCKET_BROADCAST_USER_LOGOUT = 'SOCKET_BROADCAST_USER_LOGOUT';
