export const SOCKET_IS_TYPING = 'SOCKET_IS_TYPING';
export const SOCKET_IS_NOT_TYPING = 'SOCKET_IS_NOT_TYPING';
export const SOCKET_BROADCAST_IS_TYPING = 'SOCKET_BROADCAST_IS_TYPING';
export const SOCKET_BROADCAST_IS_NOT_TYPING = 'SOCKET_BROADCAST_IS_NOT_TYPING';
