export const FETCH_ACTIVE_USER = 'FETCH_ACTIVE_USER';
export const EDIT_ACTIVE_USER = 'EDIT_ACTIVE_USER';
export const SOCKET_EDIT_ACTIVE_USER = 'SOCKET_EDIT_ACTIVE_USER';
export const SOCKET_BROADCAST_EDIT_ACTIVE_USER = 'SOCKET_BROADCAST_EDIT_ACTIVE_USER';
export const SEARCH_USER = 'SEARCH_USER';
