export const FETCH_ACTIVE_USER = 'FETCH_ACTIVE_USER';
export const EDIT_ACTIVE_USER = 'EDIT_ACTIVE_USER';
export const SEARCH_USER = 'SEARCH_USER';
export const BLOCK_USER = 'BLOCK_USER';
export const UNBLOCK_USER = 'UNBLOCK_USER';
